/*
 Generated by typeshare 1.13.4
*/

export interface LibrarySummary {
	library_id: string;
	display_name: string;
	/** Non-tombstoned photos. */
	count: number;
}

export interface ResourceInfo {
	resource_type: string;
	content_hash: string;
	ext: string;
	size_bytes: number;
}

export interface PhotoDetail {
	photo_id: string;
	library_id: string;
	cloud_id?: string;
	captured_at?: string;
	ingested_at: string;
	media_type: string;
	media_subtypes: string[];
	pixel_width: number;
	pixel_height: number;
	orientation: number;
	duration_ms: number;
	camera_make?: string;
	camera_model?: string;
	lat?: number;
	lon?: number;
	favorite: boolean;
	group_id?: string;
	group_type?: string;
	group_index: number;
	group_is_pick?: boolean;
	resources: ResourceInfo[];
}

export interface PhotoSummary {
	photo_id: string;
	library_id: string;
	captured_at?: string;
	media_type: string;
	is_live_photo: boolean;
	pixel_width: number;
	pixel_height: number;
	orientation: number;
	duration_ms: number;
	favorite: boolean;
	media_subtypes: string[];
	group_id?: string;
	group_type?: string;
}

export interface PhotoPage {
	items: PhotoSummary[];
	next_cursor?: string;
}

