use anyhow::Result;
use bollard::Docker;
use reqwest::Client;
use std::collections::HashSet;
use std::time::{Duration, Instant};

use crate::NodeInfo;
use crate::tests::files::{
    download_file_from_all_nodes_with_timeout, get_fragment_distribution,
    trigger_fragment_inventory_sync_all, upload_file, verify_all_identical,
    wait_for_fragment_distribution,
};
use crate::tests::persistence::stop_node;
use crate::tests::{Check, TestResult, TestScenario, print_and_add_check};

/// Re-encode after departure (RFC-STORAGE-001 Repair; RFC-STORAGE-002 S6).
///
/// Kill one node, drive metrics + policy ticks until its absence outlives
/// its (genesis-shrunk) decay tier and it leaves the storage view, then
/// assert the elected repairer regenerates every class the dead node held
/// — from ciphertext, byte-verified against the manifest — and the file
/// stays fully downloadable from the survivors.
///
/// The auto-managed runner seeds tiny tiers AND a tiny availability
/// bucket (decay_tiers=15,30,60,120; availability_step_secs=5) through
/// the genesis policy, so departure is seconds-scale.
pub struct ReencodeAfterDeparture;

async fn trigger_metrics(client: &Client, node: &NodeInfo) {
    let url = format!(
        "http://{}:{}/metrics/trigger",
        node.ip_address, node.port
    );
    // A dead peer costs ~25s of measurement timeouts server-side; a short
    // client timeout would cancel the axum handler BEFORE it submits the
    // metrics tx (observed: empty metrics table, tiers never derived).
    let _ = client
        .get(&url)
        .header("Authorization", format!("Bearer {}", node.jwt_token))
        .timeout(Duration::from_secs(150))
        .send()
        .await;
}

async fn trigger_tick(client: &Client, node: &NodeInfo) {
    let url = format!(
        "http://{}:{}/maintenance/policy-tick",
        node.ip_address, node.port
    );
    let _ = client
        .post(&url)
        .header("Authorization", format!("Bearer {}", node.jwt_token))
        .timeout(Duration::from_secs(60))
        .send()
        .await;
}

async fn view_members(client: &Client, node: &NodeInfo) -> Result<Vec<i32>> {
    #[derive(serde::Deserialize)]
    struct View {
        members: Vec<i32>,
    }
    let url = format!("http://{}:{}/storage/view", node.ip_address, node.port);
    let resp = client
        .get(&url)
        .header("Authorization", format!("Bearer {}", node.jwt_token))
        .timeout(Duration::from_secs(15))
        .send()
        .await?;
    anyhow::ensure!(resp.status().is_success(), "HTTP {}", resp.status());
    Ok(resp.json::<View>().await?.members)
}

impl TestScenario for ReencodeAfterDeparture {
    fn name(&self) -> &'static str {
        "re-encode-after-departure"
    }

    fn description(&self) -> &'static str {
        "A departed node's fragment classes are regenerated by the elected repairer"
    }

    async fn run(
        &self,
        mesh_id: u32,
        nodes: &[NodeInfo],
        _flags: &[String],
    ) -> Result<TestResult> {
        let start = Instant::now();
        let mut result = TestResult::new();
        let client = Client::new();

        let timestamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_millis();
        let filename = format!("test-reenc-{}.txt", timestamp);
        let contents = format!("HopNet re-encode test {}", timestamp).into_bytes();
        let full_path = format!("/{}", filename);

        println!("\nRunning re-encode-after-departure checks:");

        // 1. Upload + distribute + settle inventory.
        let upload_ok = upload_file(&nodes[0], "/", &filename, contents.clone())
            .await
            .is_ok();
        let dist_ok = upload_ok
            && wait_for_fragment_distribution(&nodes[0], &full_path, Duration::from_secs(30))
                .await
                .is_ok();
        let _ = trigger_fragment_inventory_sync_all(nodes).await;
        // Baseline metrics round pre-kill: seeds the availability grid so
        // the victim has presence history before its absence starts.
        trigger_metrics(&client, &nodes[0]).await;
        let mut settled = false;
        let settle_start = Instant::now();
        let mut settle_round = 0u32;
        while settle_start.elapsed() < Duration::from_secs(90) {
            // Re-trigger periodically: a laggard's self-check tx can be
            // eaten by the known laggard-sync flake; the differential is
            // idempotent so re-triggering is free.
            if settle_round % 5 == 4 {
                let _ = trigger_fragment_inventory_sync_all(nodes).await;
            }
            settle_round += 1;
            if let Ok(dist) = get_fragment_distribution(&nodes[0], &full_path).await
                && !dist.fragments.is_empty()
                && dist
                    .fragments
                    .iter()
                    .all(|f| !f.nodes_with_fragment.is_empty())
            {
                settled = true;
                break;
            }
            tokio::time::sleep(Duration::from_secs(2)).await;
        }
        print_and_add_check(
            &mut result,
            Check {
                name: "Upload, distribute, settle inventory".to_string(),
                passed: dist_ok && settled,
                detail: None,
            },
        );
        if !(dist_ok && settled) {
            result.duration = start.elapsed();
            return Ok(result);
        }

        // 2. Record the victim's classes, then kill it.
        let victim = &nodes[2];
        let dist = get_fragment_distribution(&nodes[0], &full_path).await?;
        let victim_classes: Vec<u32> = dist
            .fragments
            .iter()
            .filter(|f| f.nodes_with_fragment.contains(&(victim.node_id as i32)))
            .map(|f| f.local_index)
            .collect();
        let docker = Docker::connect_with_local_defaults()?;
        let stop_ok = stop_node(&docker, mesh_id, victim.node_id).await.is_ok();
        print_and_add_check(
            &mut result,
            Check {
                name: format!("Stop node {} (held {} classes)", victim.node_id, victim_classes.len()),
                passed: stop_ok && !victim_classes.is_empty(),
                detail: Some(format!("classes: {victim_classes:?}")),
            },
        );
        if !stop_ok {
            result.duration = start.elapsed();
            return Ok(result);
        }

        // 3. Drive metrics + ticks until the victim decays out of the
        // storage view (absence must outlive its 15..120s tier at 5s
        // buckets).
        let survivors = &nodes[..2];
        let mut departed = false;
        let decay_start = Instant::now();
        while decay_start.elapsed() < Duration::from_secs(300) {
            trigger_metrics(&client, &nodes[0]).await;
            trigger_tick(&client, &nodes[0]).await;
            trigger_tick(&client, &nodes[1]).await;
            if let Ok(members) = view_members(&client, &nodes[0]).await
                && !members.contains(&(victim.node_id as i32))
            {
                departed = true;
                break;
            }
            tokio::time::sleep(Duration::from_secs(3)).await;
        }
        print_and_add_check(
            &mut result,
            Check {
                name: "Victim decayed out of the storage view".to_string(),
                passed: departed,
                detail: Some(format!("after {:.0}s", decay_start.elapsed().as_secs_f64())),
            },
        );
        if !departed {
            result.duration = start.elapsed();
            return Ok(result);
        }

        // 4. Keep ticking until every class the victim held has a live
        // holder among the survivors (repairer re-encodes, self-check
        // attests).
        let survivor_ids: HashSet<i32> = survivors.iter().map(|n| n.node_id as i32).collect();
        let mut regenerated = false;
        let repair_start = Instant::now();
        while repair_start.elapsed() < Duration::from_secs(180) {
            trigger_tick(&client, &nodes[0]).await;
            trigger_tick(&client, &nodes[1]).await;
            let _ = trigger_fragment_inventory_sync_all(survivors).await;
            tokio::time::sleep(Duration::from_secs(3)).await;
            if let Ok(dist) = get_fragment_distribution(&nodes[0], &full_path).await
                && !dist.fragments.is_empty()
                && dist.fragments.iter().all(|f| {
                    f.nodes_with_fragment
                        .iter()
                        .any(|n| survivor_ids.contains(n))
                })
            {
                regenerated = true;
                break;
            }
        }
        print_and_add_check(
            &mut result,
            Check {
                name: "Every class regenerated on survivors".to_string(),
                passed: regenerated,
                detail: Some(format!("after {:.0}s", repair_start.elapsed().as_secs_f64())),
            },
        );

        // 5. File downloadable from both survivors, byte-identical.
        let downloads_ok = match download_file_from_all_nodes_with_timeout(
            survivors,
            &full_path,
            Duration::from_secs(15),
        )
        .await
        {
            Ok(data) => verify_all_identical(&data).is_ok() && data[0] == contents,
            Err(_) => false,
        };
        print_and_add_check(
            &mut result,
            Check {
                name: "File downloadable from survivors".to_string(),
                passed: downloads_ok,
                detail: None,
            },
        );

        result.details = format!(
            "Victim's {} classes regenerated after departure; data intact on survivors",
            victim_classes.len()
        );
        result.duration = start.elapsed();
        Ok(result)
    }
}
