#!/bin/bash
set -euo pipefail

# Stage 0: Generate Swift types from Rust types
# This must run before building the Swift FileProvider extension

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"

echo "🔧 Stage 0: Generating Swift types from Rust types..."

# Check if typeshare is installed
if ! command -v typeshare &> /dev/null && ! command -v ~/.cargo/bin/typeshare &> /dev/null; then
    echo "⚠️  typeshare not found. Installing..."
    cargo install typeshare-cli
fi

# Determine typeshare path
if command -v typeshare &> /dev/null; then
    TYPESHARE="typeshare"
else
    TYPESHARE="$HOME/.cargo/bin/typeshare"
fi

# Define paths
COMMON_SRC="$PROJECT_ROOT/common/src"
OUTPUT_FILE="$PROJECT_ROOT/apple/HopNetFileProvider/Sources/HopNetFileProviderExtension/Generated/HopNetTypes.swift"
OUTPUT_DIR="$(dirname "$OUTPUT_FILE")"

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Generate Swift types
echo "🔄 Running typeshare..."
"$TYPESHARE" \
    --config-file "$PROJECT_ROOT/typeshare.toml" \
    --lang swift \
    --output-file "$OUTPUT_FILE" \
    "$COMMON_SRC"

if [ $? -eq 0 ]; then
    echo "✅ Swift types generated successfully"
    echo "📄 Output: $OUTPUT_FILE"

    # Post-process Swift types
    echo "🔧 Post-processing Swift types..."

    # Remove TakeoutRecord (not needed for FileProvider)
    if grep -q "TakeoutRecord" "$OUTPUT_FILE"; then
        perl -i -ne 'print unless /^\/\/\/ Takeout record for user data export requests$/ .. /^}$/' "$OUTPUT_FILE"
        echo "  ✓ Removed TakeoutRecord"
    fi

    # Replace 'number' type with 'UInt64' (typeshare's 'number' is for TypeScript)
    if grep -q ": number" "$OUTPUT_FILE"; then
        perl -i -pe 's/: number/: UInt64/g' "$OUTPUT_FILE"
        echo "  ✓ Replaced 'number' type with 'UInt64'"
    fi

    echo "✅ Swift types post-processed"
else
    echo "❌ Failed to generate Swift types"
    exit 1
fi

# RFC-022 S4: emit the client identity constant from the workspace
# version (the single authoritative token, [workspace.package] in the
# root Cargo.toml). Swift has no compile-time env seam, so this is the
# generated-file sibling of Rust's env!("CARGO_PKG_VERSION").
VERSION_FILE="$OUTPUT_DIR/HopNetVersion.swift"
WORKSPACE_VERSION="$(grep -m1 '^version = "' "$PROJECT_ROOT/Cargo.toml" | sed 's/^version = "\(.*\)"$/\1/')"
IFS='.' read -r V_YEAR V_MONTH V_COUNTER <<< "$WORKSPACE_VERSION"
if ! [[ "$V_YEAR" =~ ^[0-9]{4}$ && "$V_MONTH" =~ ^[0-9]+$ && "$V_COUNTER" =~ ^[0-9]+$ ]]; then
    echo "❌ Workspace version '$WORKSPACE_VERSION' is not CalVer YYYY.M.N"
    exit 1
fi
VERSION_CODE=$((V_YEAR * 10000 + V_MONTH * 100 + V_COUNTER))
cat > "$VERSION_FILE" << EOF
// Generated by scripts/macos/00-generate-swift-types.sh — do not edit.
// The workspace CalVer identity this build was generated from
// (RFC-022): ${WORKSPACE_VERSION} encoded as year*10000 + month*100 + counter.
public let hopNetClientVersionCode: UInt32 = ${VERSION_CODE}
public let hopNetClientVersionHeader: String = "x-hopnet-client-version"
EOF
echo "✅ Version constant generated: ${WORKSPACE_VERSION} -> ${VERSION_CODE}"

echo "✅ Stage 0 complete: Swift types generated"