use axum::{
    extract::State, 
    response::IntoResponse,
    http::StatusCode,
    Json
};
use serde::{Serialize,Deserialize};


use crate::db::Sequence;
use crate::AppState;
use crate::{
    db,
    db::User,
};
use crate::types::Node;

#[derive(Serialize, Deserialize, Debug)]
pub struct ThisNode {
    pub node_id: i32
}

#[derive(Serialize, Deserialize, Debug)]
pub struct InitialSetupPayload {
    pub username: String,
    pub password: String,
    pub node_name: String,
    pub ip_address: String,
    pub port: i32,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct SyncSetupObject {
    pub users: Vec<User>,
    pub nodes: Vec<Node>,
    pub sequences: Vec<Sequence>,
    pub yournode: ThisNode,
}

pub async fn get_setup(
    State(app_state): State<AppState>,
) -> impl IntoResponse {
    match db::get_initial_setup(&app_state.db) {
        Ok(setupstatus) => (setupstatus, hex::encode(app_state.public_key.to_bytes())),
        Err(_) => (StatusCode::INTERNAL_SERVER_ERROR, String::new())
    }
}

// join a network, it's put by another device
pub async fn put_setup(
    State(app_state): State<AppState>,
    Json(payload): Json<SyncSetupObject>
) -> impl IntoResponse {
    match db::put_join_setup(&app_state.db, payload, app_state.private_key.as_bytes()) {
        Ok(()) => StatusCode::CREATED,
        Err(_) => StatusCode::INTERNAL_SERVER_ERROR
    }
}

// full setup from scratch
pub async fn post_setup(
    State(app_state): State<AppState>,
    Json(payload): Json<InitialSetupPayload>
) -> impl IntoResponse {
    // Construct User and Node from the simplified payload
    let user = User {
        user_id: 0, // Will be generated by the database
        username: payload.username,
        password: payload.password,
    };

    let node = Node {
        node_id: 0, // Will be generated by the database
        name: payload.node_name,
        ip_address: payload.ip_address,
        port: payload.port,
        owner: 0, // Will be set to the generated user_id
        pubkey: crate::types::PubKey::from_bytes(vec![]), // Placeholder, will use app_state.public_key
    };

    match db::post_initial_setup(&app_state.db, user, node, app_state.public_key.as_bytes(), app_state.private_key.as_bytes()) {
        Ok(()) => StatusCode::CREATED,
        Err(_) => StatusCode::INTERNAL_SERVER_ERROR
    }
}