use axum::{
    extract::State, 
    response::IntoResponse,
    http::StatusCode,
    Json
};
use serde::{Serialize,Deserialize};


use crate::consensus::types::{ConsensusPhase, Block};
use crate::consensus::QuorumCertificate;
use crate::db::Sequence;
use crate::AppState;
use crate::{
    db::setup,
    db::User,
};
use crate::types::{Blake3Hash, Node};

#[derive(Serialize, Deserialize, Debug)]
pub struct ThisNode {
    pub node_id: i32,
    pub current_phase: ConsensusPhase,
    pub current_view: i32,
    pub prepared_block_hash: Option<Blake3Hash>,
    pub committed_block_hash: Blake3Hash,
    pub highest_qc_block_hash: Blake3Hash
}

#[derive(Serialize, Deserialize, Debug)]
pub struct InitialSetupPayload {
    pub username: String,
    pub password: String,
    pub node_name: String,
    pub ip_address: String,
    pub port: i32,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct SyncSetupObject {
    pub users: Vec<User>,
    pub nodes: Vec<Node>,
    pub sequences: Vec<Sequence>,
    pub blocks: Vec<Block>,
    pub validators: Vec<Validator>,
    pub quorum_certificates: Vec<QuorumCertificate>,
    pub yournode: ThisNode,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct Validator {
    pub effective_height: i32,
    pub node_id: i32,
    pub is_active: bool
}

pub async fn get_setup(
    State(app_state): State<AppState>,
) -> impl IntoResponse {
    match setup::get_initial_setup(&app_state.db) {
        Ok(setupstatus) => (setupstatus, app_state.public_key),
        Err(_) => (StatusCode::INTERNAL_SERVER_ERROR, app_state.public_key)
    }
}

// join a network, it's put by another device
pub async fn put_setup(
    State(app_state): State<AppState>,
    Json(payload): Json<SyncSetupObject>
) -> impl IntoResponse {
    match setup::put_join_setup(&app_state.db, payload, app_state.private_key) {
        Ok(()) => StatusCode::CREATED,
        Err(_) => StatusCode::INTERNAL_SERVER_ERROR
    }
}

// full setup from scratch
pub async fn post_setup(
    State(app_state): State<AppState>,
    Json(payload): Json<InitialSetupPayload>
) -> impl IntoResponse {
    // Construct User and Node from the simplified payload
    let user = User {
        user_id: 0, // Will be generated by the database
        username: payload.username,
        password: payload.password,
    };

    let node = Node {
        node_id: 0, // Will be generated by the database
        name: payload.node_name,
        ip_address: payload.ip_address,
        port: payload.port,
        owner: 0, // Will be set to the generated user_id
        pubkey: app_state.public_key, // Placeholder, will use app_state.public_key
    };

    match setup::post_initial_setup(&app_state.db, user, node, app_state.public_key, app_state.private_key) {
        Ok(()) => StatusCode::CREATED,
        Err(_) => StatusCode::INTERNAL_SERVER_ERROR
    }
}