use axum::{
    extract::State, 
    response::IntoResponse,
    http::StatusCode,
    Json
};
use serde::{Serialize,Deserialize};
use crate::consensus::functions::generate_ed25519_key;
use crate::{PubKey, PrivKey, UserKeys};

use crate::consensus::types::{ConsensusPhase, Block};
use crate::consensus::QuorumCertificate;
use crate::db::Sequence;
use crate::AppState;
use crate::{
    db::setup,
    db::User,
};
use crate::types::{Blake3Hash, Node};

#[derive(Serialize, Deserialize, Debug)]
pub struct ThisNode {
    pub node_id: i32,
    pub current_phase: ConsensusPhase,
    pub current_view: i32,
    pub prepared_block_hash: Option<Blake3Hash>,
    pub committed_block_hash: Blake3Hash,
    pub highest_qc_block_hash: Blake3Hash
}

#[derive(Serialize, Deserialize, Debug)]
pub struct InitialSetupPayload {
    pub username: String,
    pub password: String,
    pub node_name: String,
    pub ip_address: String,
    pub port: i32,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct SyncSetupObject {
    pub users: Vec<User>,
    pub nodes: Vec<Node>,
    pub sequences: Vec<Sequence>,
    pub blocks: Vec<Block>,
    pub validators: Vec<Validator>,
    pub quorum_certificates: Vec<QuorumCertificate>,
    pub yournode: ThisNode,
    pub user_privkey: PrivKey
}

#[derive(Serialize, Deserialize, Debug)]
pub struct Validator {
    pub effective_height: i32,
    pub node_id: i32,
    pub is_active: bool
}

pub async fn get_setup(
    State(app_state): State<AppState>,
) -> impl IntoResponse {
    match setup::get_initial_setup(&app_state.db) {
        Ok(setupstatus) => (setupstatus, app_state.public_key),
        Err(_) => (StatusCode::INTERNAL_SERVER_ERROR, app_state.public_key)
    }
}

// join a network, it's put by another device
pub async fn put_setup(
    State(app_state): State<AppState>,
    Json(payload): Json<SyncSetupObject>
) -> Result<StatusCode, StatusCode> {
    // Extract user keys from payload
    let user_private_key = payload.user_privkey.clone();
    
    // Find the corresponding user's public key
    // Assuming the user's private key corresponds to the first user in the payload
    let user_public_key = payload.users.get(0)
        .ok_or(StatusCode::BAD_REQUEST)?
        .pubkey;
    
    let user_keys = UserKeys {
        private_key: user_private_key,
        public_key: user_public_key,
    };
    
    // Set user keys in app state (can only be done once)
    app_state.user_keys.set(user_keys)
        .map_err(|_| StatusCode::CONFLICT)?; // Already initialized
    
    // Initialize SIV keys from user private key
    app_state.initialize_siv_keys()?;
    
    match setup::put_join_setup(&app_state.db, payload, app_state.private_key) {
        Ok(()) => Ok(StatusCode::CREATED),
        Err(_) => Err(StatusCode::INTERNAL_SERVER_ERROR)
    }
}

// full setup from scratch
pub async fn post_setup(
    State(app_state): State<AppState>,
    Json(payload): Json<InitialSetupPayload>
) -> Result<StatusCode, StatusCode> {

    let (user_priv_key, user_pub_key) = generate_ed25519_key();
    
    let user_keys = UserKeys {
        private_key: PrivKey(user_priv_key),
        public_key: PubKey(user_pub_key),
    };
    
    // Set user keys in app state (can only be done once)
    app_state.user_keys.set(user_keys.clone())
        .map_err(|_| StatusCode::CONFLICT)?; // Already initialized
    
    // Initialize SIV keys from user private key
    app_state.initialize_siv_keys()?;

    // Construct User and Node from the simplified payload
    let user = User {
        user_id: 0, // Will be generated by the database
        username: payload.username,
        password: payload.password,
        pubkey: user_keys.public_key,
    };

    let node = Node {
        node_id: 0, // Will be generated by the database
        name: payload.node_name,
        ip_address: payload.ip_address,
        port: payload.port,
        owner: 0, // Will be set to the generated user_id
        pubkey: app_state.public_key, // Placeholder, will use app_state.public_key
    };

    match setup::post_initial_setup(&app_state.db, user, node, app_state.public_key, app_state.private_key, user_keys.private_key) {
        Ok(()) => Ok(StatusCode::CREATED),
        Err(_) => Err(StatusCode::INTERNAL_SERVER_ERROR)
    }
}
